export const values=[1,2,3,4,5,6,7,8,9,10];
const prob=v=>v===10?4/13:1/13;
export function total(cards){const raw=cards.reduce((a,c)=>a+(typeof c==='number'?c:c.v),0),ace=cards.some(c=>(typeof c==='number'?c:c.v)===1);return {n:raw+(ace&&raw+10<=21?10:0),soft:ace&&raw+10<=21,raw,ace};}
const dealerCache=new Map();
export function dealerDistribution(up){if(dealerCache.has(up))return dealerCache.get(up);const memo=new Map();function visit(raw,ace){const t=raw+(ace&&raw+10<=21?10:0);if(t>=17)return {[t>21?'bust':t]:1};const key=raw+':'+ace;if(memo.has(key))return memo.get(key);const out={};for(const c of values){const d=visit(raw+c,ace||c===1);for(const k in d)out[k]=(out[k]||0)+prob(c)*d[k];}memo.set(key,out);return out;}const out={};const excluded=up===1?10:up===10?1:0;const normal=1-(excluded?prob(excluded):0);for(const hole of values){if(hole===excluded)continue;const d=visit(up+hole,up===1||hole===1);for(const k in d)out[k]=(out[k]||0)+prob(hole)/normal*d[k];}dealerCache.set(up,out);return out;}
export function evaluate(cards,up,legal){const d=dealerDistribution(up),memo=new Map();function stand(raw,ace){const n=raw+(ace&&raw+10<=21?10:0);if(n>21)return -1;let ev=0;for(const k in d)ev+=d[k]*(k==='bust'||n>Number(k)?1:n===Number(k)?0:-1);return ev;}function best(raw,ace){const n=raw+(ace&&raw+10<=21?10:0);if(n>=21)return stand(raw,ace);const k=raw+':'+ace;if(memo.has(k))return memo.get(k);const ev=Math.max(stand(raw,ace),hit(raw,ace));memo.set(k,ev);return ev;}function hit(raw,ace){return values.reduce((sum,c)=>sum+prob(c)*best(raw+c,ace||c===1),0);}function double(raw,ace){return values.reduce((sum,c)=>sum+prob(c)*2*stand(raw+c,ace||c===1),0);}const t=total(cards),ev={};if(legal.includes('stand'))ev.stand=stand(t.raw,t.ace);if(legal.includes('hit'))ev.hit=hit(t.raw,t.ace);if(legal.includes('double'))ev.double=double(t.raw,t.ace);if(legal.includes('surrender'))ev.surrender=-.5;if(legal.includes('split')){const v=cards[0].v??cards[0];ev.split=2*values.reduce((sum,c)=>{const raw=v+c,ace=v===1||c===1;return sum+prob(c)*(v===1?stand(raw,ace):Math.max(best(raw,ace),double(raw,ace)));},0);}return ev;}
export class Game{
 constructor(){this.bank=1000;this.phase='ready';this.hands=[];this.dealer=[];this.rounds=[];this.decisions=[];this.shoe=[];this.index=0;this.insurance=0;this.message='Choose your opening bet. The table is yours.';this.shuffles=0;this.shuffle();}
 shuffle(){this.seen=Array(11).fill(0);this.shoe=[];for(let d=0;d<6;d++)for(const s of ['♠','♥','♦','♣'])for(let r=1;r<=13;r++)this.shoe.push({v:Math.min(r,10),r:r===1?'A':r===11?'J':r===12?'Q':r===13?'K':String(r),s});for(let i=this.shoe.length-1;i>0;i--){const a=new Uint32Array(1);let x;const lim=4294967296-(4294967296%(i+1));do{globalThis.crypto.getRandomValues(a);x=a[0];}while(x>=lim);const j=x%(i+1);[this.shoe[i],this.shoe[j]]=[this.shoe[j],this.shoe[i]];}this.shuffles++;}
 frame(message,flip=null){if(!this.onFrame)return;const {onFrame,...state}=this;this.onFrame({...structuredClone(state),message,flip});}
 draw(exposed=true){if(!this.shoe.length)throw Error('Shoe exhausted');const card=this.shoe.pop();if(exposed)this.seen[card.v]++;return card;}
 revealHole(){if(!this.holeRevealed&&this.dealer[1]){this.seen[this.dealer[1].v]++;this.holeRevealed=true;}}
 shoeContext(){const unseen=Array.from({length:11},(_,v)=>v?(v===10?96:24)-this.seen[v]:0);return {number:this.shuffles,remaining:this.shoe.length,unseen,unknown:unseen.reduce((a,b)=>a+b,0),seen:[...this.seen],hidden:!!this.dealer[1]&&!this.holeRevealed,peeked:this.phase==='playing'};}
 legal(){if(this.phase==='insurance')return ['decline',...(this.bank>=this.hands[0].bet/2?['insure']:[])];if(this.phase!=='playing')return [];const h=this.hands[this.index];return ['hit','stand',...(h.cards.length===2&&this.bank>=h.bet?['double']:[]),...(h.cards.length===2&&!h.split?['surrender']:[]),...(h.cards.length===2&&this.hands.length===1&&h.cards[0].v===h.cards[1].v&&this.bank>=h.bet?['split']:[])];}
 deal(bet){if(!['ready','between'].includes(this.phase))throw Error('Finish the current hand first.');if(!Number.isFinite(bet)||bet<1||bet>this.bank||(bet!==this.bank&&Math.abs(bet*2-Math.round(bet*2))>.0001))throw Error('Choose at least $1 in $0.50 steps, or bet your full balance. Your bet cannot exceed your bankroll.');if(this.shoe.length<=78)this.shuffle();this.shoeAtBet=this.shoeContext();this.holeRevealed=false;this.start=this.bank;this.wager=bet;this.exposure=bet;this.bank-=bet;this.index=0;this.insurance=0;this.insuranceNet=0;this.phase='dealing';this.dealer=[];this.hands=[{cards:[this.draw()],bet,split:false,done:false}];this.frame('Dealing your first card…','hand-0-0');this.dealer=[this.draw()];this.frame('Dealing to the house…','dealer-0');this.hands[0].cards.push(this.draw());this.frame('Dealing your second card…','hand-0-1');this.dealer.push(this.draw(false));this.opening=this.hands[0].cards.map(c=>({...c}));this.frame('Dealer takes a face-down card.');this.phase='playing';this.message='Your move.';if(this.dealer[0].v===1){this.phase='insurance';this.message='Dealer shows an ace. Insurance?';}else this.peek();}
 peek(){const h=this.hands[0],dn=total(this.dealer).n===21,pn=total(h.cards).n===21;if(dn||pn){this.phase='settling';this.revealHole();this.frame('Dealer reveals the hole card…','dealer-1');h.done=true;h.result=dn&&pn?'Push':pn?'Blackjack':'Dealer blackjack';h.return=dn?(pn?h.bet:0):h.bet*2.5;this.finish();}else{this.phase='playing';this.message='Your move. Dealer has no blackjack.';}}
 act(action){const legal=this.legal();if(!legal.includes(action))throw Error('That action is not available.');const h=this.hands[this.index];if(this.phase==='insurance'){this.frame(action==='insure'?'Insurance placed. Checking for blackjack…':'Insurance declined. Checking for blackjack…');const stake=h.bet/2,shoe=this.shoeContext(),ev={decline:0,...(legal.includes('insure')?{insure:3*shoe.unseen[10]/shoe.unknown-1}:{})};this.record(action,ev,stake,'insurance');if(action==='insure'){this.bank-=stake;this.exposure+=stake;this.insurance=stake;if(total(this.dealer).n===21){this.bank+=stake*3;this.insuranceNet=stake*2;}else this.insuranceNet=-stake;}this.peek();return;}
 const ev=evaluate(h.cards,this.dealer[0].v,legal);this.record(action,ev,h.bet,h.cards.length===2&&h.cards[0].v===h.cards[1].v?'pair':total(h.cards).soft?'soft':'hard');
 if(action==='hit'){h.cards.push(this.draw());this.frame('Hit. Your next card…',`hand-${this.index}-${h.cards.length-1}`);if(total(h.cards).n>=21)h.done=true;}
 if(action==='stand'){h.done=true;this.frame(`Standing on ${total(h.cards).n}.`);}
 if(action==='double'){this.bank-=h.bet;this.exposure+=h.bet;h.bet*=2;h.cards.push(this.draw());this.frame('Double down. One final card…',`hand-${this.index}-${h.cards.length-1}`);h.done=true;}
 if(action==='surrender'){h.done=true;h.result='Surrender';h.return=h.bet/2;this.frame('Surrender. Half your wager is returned.');}
 if(action==='split'){this.bank-=h.bet;this.exposure+=h.bet;const [a,b]=h.cards;this.hands=[{cards:[a],bet:h.bet,split:true,done:false},{cards:[b],bet:h.bet,split:true,done:false}];this.frame('Pair split. Two hands to play.');this.hands[0].cards.push(this.draw());this.frame('Dealing to your first hand…','hand-0-1');this.hands[1].cards.push(this.draw());this.frame('Dealing to your second hand…','hand-1-1');for(const hand of this.hands)if(a.v===1||total(hand.cards).n===21)hand.done=true;}
 this.advance();}
 record(action,ev,bet,category){const best=Object.keys(ev).reduce((a,b)=>ev[a]>=ev[b]?a:b),h=this.hands[this.index];this.decisions.push({round:this.rounds.length+1,hand:this.index+1,cards:h.cards.map(c=>({...c})),up:{...this.dealer[0]},action,best,ev,bet,category,loss:Math.max(0,ev[best]-ev[action]),legal:Object.keys(ev),bank:this.bank,opening:this.opening.map(c=>({...c})),split:!!h.split,roundStart:this.start,openingBet:this.wager,exposure:this.exposure,shoe:this.shoeContext(),earlier:this.decisions.filter(d=>d.round===this.rounds.length+1).map(d=>({hand:d.hand,action:d.action})),previousRound:this.rounds.length?{net:this.rounds.at(-1).net,bet:this.rounds.at(-1).bet}:null});}
 advance(){while(this.index<this.hands.length&&this.hands[this.index].done)this.index++;if(this.index<this.hands.length){this.message=this.hands.length>1?`Play hand ${this.index+1} of ${this.hands.length}.`:'Your move.';return;}this.phase='settling';this.revealHole();this.frame('Dealer reveals the hole card…','dealer-1');const live=this.hands.some(h=>!h.result&&total(h.cards).n<=21);if(live)while(total(this.dealer).n<17){this.dealer.push(this.draw());this.frame('Dealer draws…',`dealer-${this.dealer.length-1}`);}const dn=total(this.dealer).n;for(const h of this.hands){if(h.result)continue;const n=total(h.cards).n;h.result=n>21?'Bust':dn>21||n>dn?'Win':n===dn?'Push':'Loss';h.return=h.result==='Win'?h.bet*2:h.result==='Push'?h.bet:0;}this.finish();}
 finish(){for(const h of this.hands)this.bank+=h.return;this.bank=Math.round(this.bank*100)/100;const net=Math.round((this.bank-this.start)*100)/100;this.rounds.push({number:this.rounds.length+1,bet:this.wager,exposure:this.exposure,start:this.start,bank:this.bank,net,insuranceNet:this.insuranceNet,shoeAtBet:structuredClone(this.shoeAtBet),hands:this.hands.map(h=>({...h,cards:[...h.cards]})),dealer:[...this.dealer]});this.phase=this.bank<1?'ended':'between';this.endReason=this.bank===0?'bankrupt':this.bank<1?'minimum':null;this.message=this.hands.map((h,i)=>(this.hands.length>1?`Hand ${i+1}: `:'')+h.result).join(' · ')+(net===0?' · Even round':` · ${net>0?'+':'−'}$${Math.abs(net).toFixed(2)}`);}
 cashout(){if(!['ready','between'].includes(this.phase))throw Error('Cash out after the round finishes.');this.phase='ended';this.endReason='cashout';}
}
