import {total,values} from './engine.mjs';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const percent=n=>(n*100).toFixed(1)+'%';
const labels={hit:'hit',stand:'stand',double:'double down',split:'split',surrender:'surrender',insure:'take insurance',decline:'decline insurance'};
const rank=v=>v===1?'ace':v===10?'10/J/Q/K':String(v);
const handText=cards=>cards.map(c=>c.r+c.s).join(' + ');
const describe=cards=>`${total(cards).soft?'soft':'hard'} ${total(cards).n}`;

// The unknown pool contains the face-down hole card. Marginalize that card
// before computing the next player draw, conditioning on a failed peek.
export function nextCardProbabilities(d){
 const {unseen:u,unknown:n}=d.shoe;
 const excluded=d.shoe.peeked?(d.up.v===1?10:d.up.v===10?1:0):0;
 const eligible=n-(excluded?u[excluded]:0);
 return values.map(v=>({v,p:d.shoe.hidden?(u[v]-(v===excluded?0:u[v]/eligible))/(n-1):u[v]/n}));
}
export function decisionNarrative(d){
 if(!d.shoe)return {headline:'Decision context unavailable',situation:'This decision predates detailed shoe tracking. Start a new session for the full narrative.',choice:'',shoe:'',stakes:'',lesson:'Review the rule-specific strategy for this hand.',facts:[]};
 const t=total(d.cards),u=d.shoe.unseen,n=d.shoe.unknown,opening=d.opening||d.cards;
 const next=nextCardProbabilities(d),busting=next.filter(c=>total([...d.cards,c.v]).n>21),bust=busting.reduce((s,c)=>s+c.p,0);
 const strong=next.filter(c=>{const z=total([...d.cards,c.v]).n;return z>=19&&z<=21}).reduce((s,c)=>s+c.p,0);
 const ten=next.find(c=>c.v===10).p,delta=ten-4/13,side=d.category==='insurance';
 const prior=(d.earlier||[]).filter(a=>a.hand===d.hand&&a.action!=='decline'&&a.action!=='insure');
 let situation=`You opened with ${handText(opening)} (${describe(opening)}), facing the dealer’s ${d.up.r}${d.up.s}. `;
 if(d.split)situation+=`You had split the original pair; this is hand ${d.hand}, ${handText(d.cards)} (${describe(d.cards)}). `;
 else if(d.cards.length>2)situation+=`After ${prior.filter(a=>a.action==='hit').length} hit${prior.filter(a=>a.action==='hit').length===1?'':'s'}, your hand was ${handText(d.cards)} (${describe(d.cards)}). `;
 if(side)situation+='The dealer had not checked for blackjack yet. Your hand’s strength does not determine whether the hole card is a ten.';
 else if(d.up.v>=2&&d.up.v<=6)situation+=`The dealer’s ${d.up.v} is a vulnerable upcard: the house must keep drawing until at least 17. You can win without improving if the dealer busts, so taking a card yourself has to justify its risk.`;
 else if(d.up.v===1)situation+='The ace gives the dealer flexibility. The peek had ruled out blackjack, but it had not ruled out a strong final hand. The house stands on soft 17 here.';
 else situation+=`The dealer’s ${d.up.v===10?'ten-value card':d.up.v} can become a made hand with a ten in the hole. ${d.up.v===10?'The peek had ruled out an ace in the hole, so dealer blackjack was already excluded. ':''}A weak total cannot rely only on the house busting.`;
 let choice='',lesson='';
 if(side){const p=u[10]/n;choice=`There were ${u[10]} ten-value cards among ${n} unknown cards, so the hole card had a ${percent(p)} chance of completing blackjack. Insurance pays 2:1 and needs more than one chance in three to favor the player. Here that chance was ${p>1/3?'above':p<1/3?'below':'exactly at'} the break-even point. ${p>1/3?'Taking insurance was supported by this shoe’s visible composition.':p<1/3?'Declining avoided paying for a side bet whose price was too high.':'Taking or declining had the same expected return.'}`;lesson='Evaluate insurance using the proportion of ten-value cards still unknown, not how good your own hand looks.';}
 else if(d.best==='surrender'){choice=`Your ${describe(d.cards)} had two unattractive routes: standing left it below the dealer’s likely made hands, while hitting could bust immediately (${percent(bust)} on the next card in this shoe). Late surrender let you recover ${money(d.bet/2)} without risking the rest. The standard model prefers limiting the loss here over playing the hand out.`;lesson='Recognize surrender spots before hitting: the option disappears after the first two cards and is unavailable after a split.';}
 else if(d.best==='split'){const v=d.cards[0].v;choice=v===1?'Keeping two aces treats one as 1 and the other as 11. Splitting gives each ace a separate chance to pair with a ten-value card. At this table each split ace receives just one card, and a resulting 21 pays 1:1 rather than the natural-blackjack bonus.':v===8?'Keeping the eights gives you a fragile hard 16. Splitting replaces it with two hands starting from 8, each able to improve independently. It puts another wager at risk and can still lose both hands, but avoids having to nurse a single hard 16.':`Keeping the pair leaves ${describe(d.cards)}. Splitting starts two separate hands from ${rank(v)}, giving each a chance to build a more useful total against this upcard. Double after split is allowed, which makes favorable follow-up cards more valuable; re-splitting is not allowed.`;lesson='Treat a pair as a choice between one combined hand and two starting hands, including the extra wager and the table’s split rules.';}
 else if(d.best==='double'){choice=t.soft?`Your ace could drop from 11 to 1, so taking one card could not bust this soft hand. Doubling used that flexibility to add ${money(d.bet)} while the standard matchup favored it. The tradeoff is losing the right to hit again, even if the card leaves an awkward total.`:`From ${t.n}, one more card had a ${percent(strong)} chance of producing 19–21 in this shoe${bust>0?`, with a ${percent(bust)} immediate bust risk`:`, with no immediate bust risk`}. Doubling adds ${money(d.bet)} at this opportunity but commits you to that single draw. ${d.up.v<=6&&d.up.v!==1?'The dealer’s vulnerable upcard provides another way to win if your draw disappoints.':'The standard model favors the extra stake even against this stronger upcard.'}`;lesson='Look for doubles while you still have two cards. Balance the extra stake against the benefit of one card and the loss of further choices.';}
 else if(d.best==='hit'){if(t.soft)choice=`${t.n>=18?"Your total could look strong enough to keep, but it was soft":"Your hand was still soft"}: the ace could fall back to 1. That means the next card could not bust you. ${t.n>=18?'Against this upcard, accepting the current total gives up a useful chance to improve.':'You still needed to build a stronger hand.'} Hitting keeps the original wager and lets you reassess after seeing the card.`;else if(t.n<=11)choice=`Your ${t.n} was too low to beat any dealer hand that stands. A hit could not bust you, so standing would leave winning entirely to a dealer bust. Hitting improves or develops the hand while preserving the choice to draw again.`;else choice=`Standing on ${t.n} leaves you unable to beat a dealer finish of 17 or higher. Hitting is uncomfortable because ${busting.map(c=>rank(c.v)).join(', ')} would bust you, but doing nothing also carries a substantial risk. The standard model favors accepting that draw risk to seek a competitive hand rather than waiting only for a dealer bust.`;lesson=t.soft?'Identify whether the ace is still usable before judging a total. Soft and hard hands with the same number can need different actions.':'Compare the risk of busting with the risk of standing on a total that cannot beat a made dealer hand.';}
 else {if(t.n>=19)choice=`Your ${describe(d.cards)} was already a strong made hand. Drawing again risked turning that position into a loss${bust>0?`—${percent(bust)} of possible next draws would bust you in this shoe`:''}. ${d.cards.length===2&&d.cards[0].v===10&&d.cards[1].v===10?'Splitting tens would also break up a strong 20 and require a second wager. ':''}Standing preserves the total and lets the dealer resolve its own hand.`;else if(t.n>=17)choice=`Your ${describe(d.cards)} can beat or push some dealer finishes without another card. ${t.soft?'Although this soft hand cannot bust on the next draw, a card can reduce its effective total, and doubling forces you to keep the result.':'A hit puts this made hand at risk of busting.'} The standard model prefers keeping it against this upcard.`;else choice=`Your hard ${t.n} was not strong by itself, but the dealer’s upcard gave you a reason to wait. The house has to draw to 17; you do not. Standing makes a dealer bust your route to a win and avoids your own ${percent(bust)} next-card bust risk. If you bust first, you lose even if the dealer would later bust.`;lesson=t.n<17?'Against a vulnerable dealer, a weak player total can still be a stand: the order of busting matters.':'Do not chase 21 automatically. Judge the value of keeping your made hand before risking another card.';}
 if(!side){if(d.action!==d.best)choice+=` You chose to ${labels[d.action]}. ${d.action==='double'?`That committed a second ${money(d.bet)} and removed further hit choices.`:d.action==='surrender'?'That guaranteed losing half the wager and gave up the chance to play this position.':d.action==='split'?`That committed another ${money(d.bet)} and replaced the original hand with two separate ones.`:d.action==='stand'?'That locked in the current total.':d.action==='hit'?'That exposed the hand to another card, after which its total and remaining options could change.':''} ${d.loss<=.005?'The standard model treats the two choices as nearly equal; this is a close spot, not a clear mistake.':''}`;else choice+=` Your choice to ${labels[d.action]} followed that logic.`;}
 else choice+=` You chose to ${labels[d.action]}.`;
 const concentration=Math.abs(delta)<.002?'close to a fresh shoe’s share':`${Math.abs(delta*100).toFixed(1)} percentage points ${delta>0?'above':'below'} a fresh shoe’s share`;
 let shoe=`At that moment, shoe ${d.shoe.number} had ${d.shoe.remaining} undealt cards (${(d.shoe.remaining/52).toFixed(2)} decks). ${n} cards were unaccounted for${d.shoe.hidden?', including the dealer’s hidden card':''}: ${u[10]} ten-value cards, ${u[1]} aces, and ${u.slice(2,7).reduce((a,b)=>a+b,0)} cards worth 2–6. `;
 if(!side)shoe+=`After allowing for the hidden card${d.shoe.peeked&&(d.up.v===1||d.up.v===10)?' and the failed blackjack peek':''}, your next draw had a ${percent(ten)} chance of being ten-valued—${concentration}. ${t.soft?'Your usable ace made the next-card bust risk zero, even with tens left.':bust>0?`For your actual hand, the next-card bust risk was ${percent(bust)}.`:'Your total was low enough that no single next card could bust it.'} ${delta>.002&&t.n>=12&&!t.soft?'The extra concentration of tens increased one source of danger for your hand; those same tens can also hurt a dealer forced to draw.':delta>.002&&t.n<=11?`More tens made a strong one-card finish from a low total more available, but they can also strengthen the dealer.`:delta<-.002?'Fewer tens changed the draw mix, but that alone does not settle whether to hit, stand, or double.':'The ten-value share stayed close to its starting level; your hand and the upcard remained the main strategic features.'}`;
 else shoe+='The hidden card stayed inside that unknown pool; its actual identity was never used to judge your insurance decision.';
 let stakes=`You opened the round at ${money(d.openingBet)}, ${percent(d.openingBet/d.roundStart)} of your ${money(d.roundStart)} bankroll. ${money(d.exposure)} was already committed when you made this choice, with ${money(d.bank)} still available. `;
 if(side)stakes+=`The optional insurance cost ${money(d.bet)} more. `;
 else if(d.legal.includes('double')||d.legal.includes('split'))stakes+=`An available double${d.legal.includes('split')?' or split':''} would commit another ${money(d.bet)}. `;
 if(!side&&d.cards.length===2&&!d.legal.includes('double'))stakes+='You did not have enough available chips to double, so it was excluded from the comparison. ';
 if(!side&&d.cards.length>2)stakes+='After taking cards, doubling, splitting and surrendering were no longer available. ';
 if(d.split)stakes+='Surrender and another split were unavailable on this split hand. ';
 if(d.previousRound?.net<0&&d.openingBet>d.previousRound.bet)stakes+=`You had raised the opening bet from ${money(d.previousRound.bet)} after losing ${money(-d.previousRound.net)} in the previous round. That increased the cost of a mistake; the prior loss did not make this hand due to win. `;
 else stakes+='A bigger stake changes the dollars at risk, not which rank comes next. ';
 return {headline:side?'The insurance decision':`${describe(d.cards)} against ${d.up.v===1?'an ace':d.up.v===10?'a ten-value upcard':d.up.v}`,situation,choice,shoe,stakes,lesson,facts:next.map(c=>({rank:rank(c.v),count:u[c.v],chance:c.p,outcome:total([...d.cards,c.v]).n}))};
}
export function betNarrative(r,previous){const s=r.shoeAtBet;let text=`Before the deal, you put ${money(r.bet)} at risk from ${money(r.start)} (${percent(r.bet/r.start)}). `;if(s){const ten=s.unseen[10]/s.unknown; text+=`Shoe ${s.number} had ${s.remaining} cards left, with ${percent(ten)} of the unknown cards ten-valued. Your opening hand and the dealer’s upcard were not known yet. `;}text+=previous?.net<0&&r.bet>previous.bet?`You increased the bet after a loss, from ${money(previous.bet)} to ${money(r.bet)}. The new wager raised exposure without making a recovery due. `:previous&&r.bet===previous.bet?'You kept the same opening stake as the previous round. ':'';text+=r.bet/r.start>.05?'The stake exceeded 5% of your bankroll, so relatively few lost rounds could consume a large part of your chips. ':'This kept the opening stake within the review’s 5% risk threshold. ';text+='Card composition can affect the game, but this report does not calculate a pre-deal player edge or an optimal bet size. ';if(r.exposure>r.bet)text+=`Later decisions increased the round’s total exposure to ${money(r.exposure)}.`;return text;}
